import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import NavBar from "@/components/navbar";

import ProjectSvg from "@/components/animSvg/ProjectSvg";
import ProfileSvg from "@/components/animSvg/ProfileSvg";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Add this navItems array
const navItems = [
  {
    name: "PROJETS",
    link: "#projets",
    icon: <ProjectSvg className="ml-4" />,
  },
  {
    name: "PROFILE",
    link: "#Profile",
    icon: <ProfileSvg className="ml-4" />,
  },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <header className="h-16 flex justify-between items-center bg-secondary">
          <NavBar navItems={navItems} />

        </header>
        {children}
        <footer className="h-16 sm:bg-secondary">
          <div className="flex justify-between items-center max-w-[1200px] py-4 sm:mx-[auto] px-4">
            <p className="text-sm">© 2024 - Henri Regniez</p>
          </div>
        </footer>
      </body>
    </html>
  );
}